### PR TITLE
Forced send() to accept an `Endpoint` instead of a String

### PR DESCRIPTION
**Pull request by unpluggedsam**
This commit will force the send() to accept an `Endpoint` instead of a String. This insures that invalid `URL`'s will not be passed in.

Also, a minor error that I noticed was that in the getInformation() and getEndpointThroughAPI() they converted the endpoints to `URL`'s by using toString() instead of getURL().

### CODE REVIEW

**Comment by Black-Plasma** [comment]
What about query parameters?

**Comment by unpluggedsam** [comment]
> What about query parameters?

As I said in another issue, query parameters is another issue. We shouldn't be modifying our own URL in the code. We may want to have a factory class to handle that.

**Comment by Black-Plasma** [comment]
I wouldn't merge until we got that done then though. Can you clarify how you want it to look like please? Then i can make a PR for that.

**Comment by unpluggedsam** [comment]
> I wouldn't merge until we got that done then though. Can you clarify how you want it to look like please? Then i can make a PR for that.

https://github.com/hypixelapiwrapper/hypixel-api-java/issues/47

**Pull request closed without merging**
