### PR TITLE
Removing test files

### PR DESCRIPTION
**Pull request by NotInsertIGN**
Removed all testing directories/files
Feel my pain I did this on GitHub mobile

### CODE REVIEW

**Comment by NotInsertIGN** [comment]
In a moving car, nontheless

**Comment by ChiefChippy2** [comment]
don't drive whilst using your phone!
also how did you do that on gh mobile

**Review by Mqlvin — APPROVED** [review]
Looks good, I see no reason to keep these classes.

**Comment by ChiefChippy2** [comment]
that said, wouldn't it be more appropriate to eithe .gitignore or put the test-free directory on another branch

**Comment by Mqlvin** [comment]
> that said, wouldn't it be more appropriate to eithe .gitignore or put the test-free directory on another branch

I think the NoCachingStrategy was being used by a couple people but I'll add a .gitignore to the directory now, since that is no longer the case (at least for the moment)

**Pull request merged**
