### PR TITLE
Exception handling

### PR DESCRIPTION
**Pull request by unpluggedsam**
- Handle exceptions thrown from the API.
  ⚫ Accept codes 200 - 300 returned from API.
  ⚫ Handle codes 400, 403, 422 and 429 with custom exceptions.
  ⚫ Handle null player and guild objects with custom exceptions.
  ⚫ Handle unknown exceptions with `UnknownAPIException`.
- Refactor `PineappleException` to `NovopixelException`.
- Refactor toString() of `NovopixelException` (may want to change in the future.)

### CODE REVIEW

**Review by NotInsertIGN — COMMENTED** [review]
Looks good, except we haven't decided on a name yet. Novopixel isn't sticking as far as I know.

Awesome, I was using Novopixel as a place holder. It can be replaced in a future PR.

**Comment by Nopock** [comment]
> Looks good, except we haven't decided on a name yet. Novopixel isn't sticking as far as I know.

I'm in agreement 😄

**Comment by NotInsertIGN** [comment]
@unpluggedsam update:
I believe the name we're using is Neopixel, as far as the votes go.

**Comment by unpluggedsam** [comment]
For future reference, the refactoring of the name should've been put in another PR.

**Review by NotInsertIGN — APPROVED** [review]
Looks good

**Pull request merged**
