### PR TITLE
Finish HypixelFriend

### PR DESCRIPTION
**Pull request by unpluggedsam**
Finish HypixelFriend
- Create a class named `HypixelFriend`.
- Keeps track of when two players add each other as friends.
- Create a `UnformattedStringToUUID` class which converts plain `UUID` Strings to `UUID` objects. 
- Create methods in `HypixelPlayer` to retrieve a Players friends.

### CODE REVIEW

**Comment by Mqlvin** [comment]
Test file present samuel

**Comment by unpluggedsam** [comment]
> Test file present samuel

Apologies

**Review by Mqlvin — APPROVED** [review]
It's looking great sam - I'm not sure where this project would be without you to be honest.

**Comment by unpluggedsam** [comment]
> It's looking great sam - we wouldn't be nearly as far through this project without you.

Love you melvin <3

**Comment by Mqlvin** [comment]
> > It's looking great sam - we wouldn't be nearly as far through this project without you.
> 
> Love you melvin <3

Platonically of course

**Pull request merged**
