### PR TITLE
Unneeded package nesting

### PR DESCRIPTION
**Pull request by TheNullicorn**
- Extract packages out of `wrapper` package & delete it
- Move `caching` package inside `http`
  - Rename `caching` package to just `cache` for consistency (not using gerunds)
- Move `log` package out of `util`
- Move `Endpoint` enum from `util` to `io.http`

Miscellaneous:
- Remove `endpoints.json` resource, which has already been replaced with the `Endpoint` enum

### CODE REVIEW

**Comment by Mqlvin** [comment]
Considering we were planning to implement multiple APIs, would it be better to nest all related packages under a `Hypixel` package? It would make readability easier, and allow for expanding.

**Comment by unpluggedsam** [comment]
So what's the deal with this? I do like most of the package changes, but the wrapper package looks fine to me.

**Comment by TheNullicorn** [comment]
I think it's just me being stubborn about the `wrapper` package right now. If we just want this merged I can revert that & update it to match master

**Comment by unpluggedsam** [comment]
I think that would be ideal for now

**Review by unpluggedsam — APPROVED** [review]
I added a couple of commits, but everything looks good to merge into master now.

**Pull request merged**
